postcodenl_api:
    path: /get-postalcode-details
    defaults: { _controller: KeesschepersPostcodenlApiBundle:Default:postalcodeCheck }
    methods: ['GET']
    requirements:
        zipcode:        "[0-9A-Za-z ]+"
        address-number: "[0-9A-Za-z ]+"
